services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      RAILS_ENV: ${RAILS_ENV}
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 4000 -b '0.0.0.0'"
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - web_node_modules:/app/node_modules
    ports:
      - "3000:3000"
    environment:
      API_URL: http://backend:4000
    command: yarn run dev
volumes:
  postgres_data:
    driver: local
  web_node_modules:
    driver: local
